# netlify.toml

[build]
  command = "hugo mod get -u && hugo --gc --minify -b $DEPLOY_PRIME_URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.20"
  TZ = "Asia/Tokyo"

[context.production.environment]
  HUGO_VERSION = "0.104.1"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.104.1"
